version: "3.5"

x-share-env: &share-env
  ADMIN_PASSWORD: <CENSORED>

services:
  web:
    depends_on:
      - xss-bot
    build: ./app
    volumes:
      - ./app/:/app
    ports:
      - 8000:80/tcp
    environment:
      FLAG: FLAG{<CENSORED>}
      RECAPTCHA_PRIVATE_KEY: <CENSORED>
      <<: *share-env
  
  xss-bot:
    build: ./bot
    environment:
      <<: *share-env